// One-time sweep: for every published watch companion, lower each
// character's visibleAfter to match the earliest relationship that
// references it. Fixes relationships generated by the AI with an
// earlier visibleAfter than their endpoint characters, which silently
// gate the relationship from appearing in the viewer.
//
// Usage:
//   npx tsx scripts/backfill-companion-character-promote.ts
//
// Idempotent — safe to re-run.

import { config } from "dotenv";
config({ path: ".env.local" });
config({ path: ".env" });

async function main() {
  // Dynamic imports so lib/prisma.ts initializes against the DATABASE_URL
  // loaded by dotenv above. ESM static imports are hoisted, which would
  // run lib/prisma.ts's createPrismaClient() before config() ran and
  // leave us pointed at the placeholder localhost URL.
  const { prisma } = await import("../lib/prisma");
  const { promoteCharactersForCompanion } = await import("../lib/watch-companion-promote");

  const companions = await prisma.watchCompanion.findMany({
    where: { status: "published" },
    select: { id: true, title: true, mediaType: true, tmdbId: true },
  });

  console.log(`[backfill] scanning ${companions.length} published companions…`);

  let totalUpdated = 0;
  let touched = 0;
  for (const c of companions) {
    try {
      const result = await promoteCharactersForCompanion(c.id);
      if (result.charactersUpdated > 0) {
        touched++;
        totalUpdated += result.charactersUpdated;
        console.log(`  [${c.mediaType}#${c.tmdbId}] ${c.title}: promoted ${result.charactersUpdated} character(s) across ${result.relationshipsScanned} relationship(s)`);
      }
    } catch (err) {
      console.error(`  [${c.mediaType}#${c.tmdbId}] ${c.title}: failed —`, err);
    }
  }

  console.log(`\n[backfill] done. ${touched}/${companions.length} companions touched. ${totalUpdated} character row(s) updated total.`);
  await prisma.$disconnect();
}

main().catch((err) => { console.error(err); process.exit(1); });
